### ISSUE TITLE
Support for Knokkos custom items as recipe output

### ISSUE THREAD

**Issue by Phoenixvine32908** [WolfyScript/WolfyUtilities#39]
When you try to use a custom item as a recipe output it flickers and dissapears when you try to craft it.

**Comment by WolfyScript** [comment]
This issue seems to be related to CustomCrafting. Please open it again here https://github.com/WolfyScript/CustomCrafting-Wiki/issues

Please follow the presets that are available!
The title is a feature request and the comment describes a bug? Be more clear about what you want to report or request!

If you have any questions about opening an issue ask on the Discord server first.
